name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v0.1.0, v1.2.3

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing with PyPI

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a general version for building

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

